name: triflow_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.49.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.10.17
  - readline=8.2
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - biopython==1.85
      - biotite==1.1.0
      - biotraj==1.2.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepspeed==0.16.7
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.18.0
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - gemmi==0.6.7
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hjson==3.1.0
      - idna==3.10
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - pdbeccdutils==0.8.6
      - pillow==10.4.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - propcache==0.3.1
      - protobuf==6.31.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2023.9.6
      - requests==2.32.3
      - scipy==1.15.3
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - setuptools==80.9.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tomli==2.2.1
      - torch==2.6.0
      - torchmetrics==1.7.1
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.19.11
      - wrapt==1.17.2
      - yarl==1.20.0
